services:
  mysql:
    image: mysql:latest
    container_name: data_manager_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_manager
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./docker-data/mysql-data:/var/lib/mysql
      - ./docker-data/mysql-conf:/etc/mysql/conf.d
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+08:00
